version: "3.9"

# volumes: 
#   mysql-store:
  
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./src/:/app
    container_name: wedding
  
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    container_name: nginx
    ports:
      - 8081:80
    volumes:
      - ./src/:/app
    depends_on:
      - app
  
  db:
    image: mysql:8.0.25
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-wedding}
      MYSQL_USER: ${DB_USERNAME:-satoyuya}
      MYSQL_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
    container_name: mysql
      
volumes:
  mysql-volume:
  mysql-store:
